"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
const nav=["About","Services","Projects","Contact"];
const work=[["Harbor Offices","Commercial","photo-1497366754035-f200968a6e72"],["Northline Residence","Residential","photo-1541888946425-d81bb19240f5"],["Civic Courtyard","Public realm","photo-1511818966892-d7d671e672a2"]];
function Form(){const [sent,setSent]=useState(false);return <form onSubmit={(e:FormEvent)=>{e.preventDefault();setSent(true)}} className="grid gap-3"><input required aria-label="Name" placeholder="Your name" className="border-b border-white/30 bg-transparent py-3 outline-none placeholder:text-white/50"/><input required type="email" aria-label="Email" placeholder="Email address" className="border-b border-white/30 bg-transparent py-3 outline-none placeholder:text-white/50"/><textarea required aria-label="Project details" placeholder="Tell us about your project" rows={3} className="border-b border-white/30 bg-transparent py-3 outline-none placeholder:text-white/50"/><button className="mt-2 w-fit bg-[#F6B445] px-6 py-3 text-sm font-bold text-[#10213B]">{sent?"Request received":"Start a conversation"}</button></form>}
export default function Home(){return <main className="bg-[#F4F1EA] text-[#10213B]"><header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-7"><Link href="/" className="text-2xl font-black tracking-[-.08em]">MADAR<span className="text-[#E67A2E]">.</span></Link><nav className="hidden gap-7 text-sm font-semibold md:flex">{nav.map(x=><Link key={x} href={`/${x.toLowerCase()}`}>{x}</Link>)}</nav><Link href="/contact" className="border border-[#10213B] px-4 py-2 text-xs font-bold uppercase tracking-widest">Discuss a build</Link></header>
<section className="mx-auto grid max-w-7xl gap-8 px-6 pb-16 pt-8 lg:grid-cols-[1.05fr_.95fr] lg:items-end"><div className="pb-6"><p className="mb-7 text-xs font-bold uppercase tracking-[.22em] text-[#E67A2E]">Construction & contracting · concept project</p><h1 className="text-6xl font-black leading-[.9] tracking-[-.075em] sm:text-8xl">Built for the<br/>long view.</h1><p className="mt-8 max-w-md text-lg leading-8 text-[#445168]">Madar Build shapes resilient commercial, residential and civic spaces with clear process and accountable delivery.</p><div className="mt-9 flex gap-4"><Link href="/projects" className="bg-[#10213B] px-6 py-4 text-sm font-bold text-white">Explore our work</Link><Link href="/services" className="py-4 text-sm font-bold underline">Our services</Link></div></div><div className="relative min-h-[440px] overflow-hidden"><img src="https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=85" alt="Building under construction" className="absolute inset-0 h-full w-full object-cover"/><p className="absolute bottom-0 left-0 bg-[#E67A2E] px-5 py-4 text-xs font-bold uppercase tracking-widest text-white">Site 04 · Progress with purpose</p></div></section>
<section className="border-y border-[#10213B]/15 bg-white py-9"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-6 px-6 md:grid-cols-4">{[["12","years of craft"],["48","concept builds"],["6","core disciplines"],["1","clear partner"]].map(([n,l])=><div key={l}><p className="text-4xl font-black tracking-tighter">{n}</p><p className="mt-1 text-xs font-bold uppercase tracking-wider text-[#6A7484]">{l}</p></div>)}</div></section>
<section className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-10 md:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#E67A2E]">What we do</p><h2 className="mt-4 text-4xl font-black">One team,<br/>from ground to handover.</h2></div><div className="grid gap-px bg-[#10213B]/15 md:grid-cols-2">{[["01","General Contracting","A reliable lead for complex scopes."],["02","Construction","Detailed execution around the brief."],["03","Renovation","Thoughtful upgrades with minimal disruption."],["04","Project Management","Decisions and timelines kept aligned."]].map(([n,t,d])=><article key={n} className="bg-[#F4F1EA] p-7"><p className="text-sm font-bold text-[#E67A2E]">{n}</p><h3 className="mt-10 text-xl font-black">{t}</h3><p className="mt-3 text-sm leading-6 text-[#596579]">{d}</p></article>)}</div></div></section>
<section className="bg-[#10213B] px-6 py-24 text-white"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#F6B445]">Selected projects</p><h2 className="mt-4 text-4xl font-black">Places made to perform.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{work.map(([name,type,img])=><Link href="/projects" key={name} className="group"><div className="aspect-[4/5] overflow-hidden"><img src={`https://images.unsplash.com/${img}?auto=format&fit=crop&w=800&q=80`} alt={name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><h3 className="mt-4 font-bold">{name}</h3><p className="mt-1 text-xs text-white/55">{type}</p></Link>)}</div></div></section>
<section className="grid bg-[#E67A2E] md:grid-cols-2"><div className="min-h-[350px] bg-[url('https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1100&q=80')] bg-cover bg-center"/><div className="p-10 text-white md:p-16"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#FDE3B2]">Madar Build</p><h2 className="mt-4 text-4xl font-black">Let’s bring a solid idea into the world.</h2><Link href="/contact" className="mt-8 inline-block border border-white px-5 py-3 text-sm font-bold">Tell us what you’re planning</Link></div></section>
<footer className="bg-[#10213B] px-6 py-14 text-white"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-2"><div><p className="text-2xl font-black tracking-[-.08em]">MADAR<span className="text-[#F6B445]">.</span></p><p className="mt-4 max-w-xs text-sm leading-6 text-white/60">A fictional construction studio created as a portfolio concept.</p><div className="mt-6 flex gap-4 text-xs font-bold uppercase tracking-widest text-[#F6B445]"><a href="https://www.instagram.com/" target="_blank">Instagram</a><a href="https://www.linkedin.com/" target="_blank">LinkedIn</a></div></div><Form/></div><p className="mx-auto mt-12 max-w-7xl border-t border-white/15 pt-5 text-xs text-white/45">© 2026 Madar Build · Concept project</p></footer></main>}
