"use client";
import Link from "next/link"; import { FormEvent, useState } from "react";
const nav=["About","Services","Projects","Contact"];
function Head(){return <header className="border-b border-[#10213B]/10"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><Link href="/" className="text-2xl font-black tracking-[-.08em]">MADAR<span className="text-[#E67A2E]">.</span></Link><nav className="hidden gap-7 text-sm font-semibold md:flex">{nav.map(x=><Link key={x} href={`/${x.toLowerCase()}`}>{x}</Link>)}</nav><details className="relative md:hidden"><summary className="cursor-pointer list-none border border-[#10213B] px-3 py-2 text-xs font-bold">MENU</summary><nav className="absolute right-0 z-20 mt-2 grid min-w-40 bg-[#10213B] p-3 text-white">{nav.map(x=><Link key={x} href={`/${x.toLowerCase()}`} className="px-2 py-2">{x}</Link>)}</nav></details></div></header>}
function Form(){const[s,setS]=useState(false);return <form onSubmit={(e:FormEvent)=>{e.preventDefault();setS(true)}} className="grid gap-4 rounded-2xl bg-[#10213B] p-7 text-white"><input required aria-label="Name" placeholder="Your name" className="border-b border-white/30 bg-transparent py-3 outline-none"/><input required aria-label="Email" type="email" placeholder="Email address" className="border-b border-white/30 bg-transparent py-3 outline-none"/><textarea required aria-label="Project details" placeholder="Project outline" rows={4} className="border-b border-white/30 bg-transparent py-3 outline-none"/><button className="w-fit bg-[#F6B445] px-5 py-3 text-sm font-bold text-[#10213B]">{s?"Demo request received":"Send project inquiry"}</button><p className="text-xs text-white/50">Demo form — no real booking is made.</p></form>}
const cards=(items:string[])=><div className="grid gap-5 md:grid-cols-2">{items.map((x,i)=><article key={x} className="bg-white p-7 shadow-sm"><p className="text-xs font-black text-[#E67A2E]">0{i+1}</p><h2 className="mt-6 text-2xl font-black">{x}</h2><p className="mt-3 leading-7 text-[#596579]">A complete, considered service component designed for a practical delivery process and a professional client experience.</p><Link href="/contact" className="mt-5 inline-block text-sm font-bold underline">Discuss this</Link></article>)}</div>;
const d:Record<string,[string,string,string,React.ReactNode]>={
about:["About Madar","Built on clarity, held to a higher standard.","A fictional construction partner for commercial, residential and civic work.",<><div className="grid gap-5 md:grid-cols-3">{[["Listen","Practical goals, site constraints and priorities."],["Align","Scope, people and milestones in one clear plan."],["Deliver","Visible progress, documented decisions and protected details."]].map(([t,c])=><article key={t} className="border-t-2 border-[#E67A2E] bg-white p-7"><h2 className="text-2xl font-black">{t}</h2><p className="mt-4 text-sm leading-7 text-[#596579]">{c}</p></article>)}</div><div className="mt-12 grid gap-8 bg-[#DCE5E4] p-9 md:grid-cols-2"><h2 className="text-4xl font-black">Good builds make the next decision easier.</h2><p className="leading-8 text-[#445168]">Madar is a portfolio concept built around the details that give a construction site confidence: coordination, care and a useful record at handover.</p></div></>],
services:["Services","A complete route from brief to handover.","Focused disciplines or one accountable team around the entire project.",<><>{cards(["General Contracting","Commercial Construction","Renovation & Fit-Out","Project Management","Pre-Construction","Aftercare"])}</><div className="mt-14 border-y border-[#10213B]/15 py-10"><p className="text-xs font-bold uppercase tracking-widest text-[#E67A2E]">How work moves</p><div className="mt-5 grid grid-cols-2 gap-6 md:grid-cols-4">{["Discover","Plan","Build","Handover"].map((x,i)=><div key={x}><p className="text-4xl font-black text-[#D0A46E]">0{i+1}</p><p className="mt-2 font-bold">{x}</p></div>)}</div></div></>],
projects:["Projects","Spaces imagined for the way people use them.","Fictional project studies that show range across commercial, residential and public work.",<div className="grid gap-7 md:grid-cols-2">{[["Harbor Offices","Commercial workplace","photo-1497366754035-f200968a6e72"],["Northline Residence","Residential","photo-1541888946425-d81bb19240f5"],["Civic Courtyard","Public realm","photo-1511818966892-d7d671e672a2"],["Westyard Retail","Mixed-use","photo-1486406146926-c627a92ad1ab"]].map(([n,t,img])=><article key={n} className="overflow-hidden bg-white"><img src={`https://images.unsplash.com/${img}?auto=format&fit=crop&w=1100&q=85`} alt={n} className="aspect-[16/10] w-full object-cover"/><div className="p-7"><p className="text-xs font-bold uppercase text-[#E67A2E]">{t}</p><h2 className="mt-3 text-2xl font-black">{n}</h2><p className="mt-3 leading-7 text-[#596579]">A clear project story, material approach and delivery ambition for this fictional build.</p></div></article>)}</div>],
contact:["Contact","Let’s start with what needs to work.","Tell us about the space, timeline and priorities.",<div className="grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-widest text-[#E67A2E]">Studio</p><p className="mt-2 text-xl font-black">Fictional office, North District</p><p className="mt-2 text-[#596579]">Mon–Fri · 08:30–17:30</p></div><a href="mailto:hello@madarbuild.demo" className="font-black underline">hello@madarbuild.demo</a><p className="text-sm leading-7 text-[#596579]">All business data is fictional and used only to demonstrate a professional website experience.</p></div><Form/></div>]
};
export function Interior({page}:{page:string}){const s=d[page]??d.about;return <main className="min-h-screen bg-[#F4F1EA] text-[#10213B]"><Head/><section className="mx-auto max-w-7xl px-6 py-16 md:py-24"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#E67A2E]">{s[0]}</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.94] tracking-[-.06em] md:text-7xl">{s[1]}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#536174]">{s[2]}</p><div className="mt-16">{s[3]}</div></section><section className="bg-[#E67A2E] px-6 py-12 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 md:flex-row md:items-center"><p className="text-2xl font-black">Have a project in mind?</p><Link href="/contact" className="w-fit border border-white px-5 py-3 text-sm font-bold">Talk to Madar</Link></div></section><footer className="bg-[#10213B] px-6 py-12 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 md:flex-row"><p className="font-black">MADAR<span className="text-[#F6B445]">.</span></p><p className="text-sm text-white/60">Fictional construction company · Concept project</p></div></footer></main>}
